# version: '3.4'

services:
  backend:
    image: jinergenkai/hh-backend
    build:
      context: .
      dockerfile: HH.Api/Dockerfile
    ports:
      - "8080:8080"
      - "6789:6789"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8080;http://+:6789
        #- ASPNETCORE_Kestrel__Certificates__Default__Password=QWErty789)
        #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/fullchain.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/privkey.pem
    volumes:
      - /etc/letsencrypt/live/huynhhanh.com-0001:/https:ro
