# version: '3.4'

services:
  backend:
    image: jinergenkai/hh-backend
    build:
      context: .
      dockerfile: HH.Api/Dockerfile
    ports:
      - "8080:8080"
      - "6789:6789"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:6789;http://+:8080
